name: Purge repoless sites CDN cache when code is updated in main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Payload: ${{ github.context.payload }}"

      - name: Purge code paths on CDN
        # env: 
        #   SECRETS: ${{ secrets }}
        runs:
          using: 'node20'
          main: '.github/ci/purge-code-paths-on-cdn.js'