name: Purge repoless sites CDN cache when code is updated in main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "2"  # To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./.github/ci
        run: npm install

      - name: Purge CDN Cache for repoless sites - Site 1
        working-directory: ./.github/ci
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          HOST: ${{ secrets.SITE_1_HOST }}
          PLAN: ${{ secrets.SITE_1_PLAN }}
          APITOKEN: ${{ secrets.SITE_1_APITOKEN }}
          ZONEID: ${{ secrets.SITE_1_ZONEID }}
        run: node cf-purge-cache.js