name: Purge repoless sites CDN cache when code is updated in main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"
          echo "Event Payload: ${{ toJson(github.event.client_payload) }}"
          echo "Event: ${{ toJson(github.event) }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./.github/ci
        run: npm install

      - name: Purge CDN Cache for repoless sites
        working-directory: ./.github/ci
        env:
          tokens: ${{ toJson(secrets) }}
        run: node purge-code-across-sites.js