name: Purge repoless sites CDN cache when code is updated in main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Payload: ${{ github.context.payload }}"
      # - uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.head_ref }}
      #     # The bot user https://github.com/hlx-crn-bot is used to commit the changes. The personal access token
      #     # must be created from: https://github.com/settings/tokens
      #     # The token is then stored in the secrets of the repository.
      #     token: ${{ secrets.BOT_ACCESS_TOKEN }}
      # - name: Configure git
      #   run: |
      #     git config user.name "hlx-crn-bot"
      #     git config user.email "<>"
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      # - name: Install dependencies
      #   working-directory: ./.github/ci
      #   run: npm install

      - name: Purge code paths on CDN
        env:
          SECRETS: ${{ toJSON(secrets) }}
        working-directory: ./.github/ci
        runs:
          using: 'node20'
          main: 'purge-code-paths-on-cdn.js'